language: python
python:
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r requirements.dev.txt
  - pip install coveralls
script:
  - coverage run python manage.py test
  - flake8 .
after_success:
  - coveralls
matrix:
  allow_failures:
    - python: 3.3
    - python: pypy
