language: python
python:
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r requirements.dev.txt --use-mirrors
script:
  - python manage.py test
  - flake8 --exclude=migrations .
matrix:
  allow_failures:
    - python: 3.3
    - python: pypy
